# -*- coding: utf-8 -*-
"""Combined Footing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZ8r_oYQm0tEm5f6vuMlW2kZYujrA14c
"""

# footing_app.py
import streamlit as st
import math
import pandas as pd

st.set_page_config(page_title="Combined Footing Design Calculator", layout="wide")
st.title("Combined Footing Design Calculator — Area, Shear & Reinforcement")

# ---------------------------
# Sidebar: Inputs
# ---------------------------
st.sidebar.header("Input parameters (SI units)")

D = st.sidebar.number_input("Center to center distance between columns", min_value=0.0, value=5.0, step=0.5, format="%.3f")

st.sidebar.caption("For **first** column:")
P_D1 = st.sidebar.number_input("Dead axial load P_D1 (kN)", value=200.0, step=10.0, format="%.2f")
P_L1 = st.sidebar.number_input("Live axial load P_L1 (kN)", value=100.0, step=10.0, format="%.2f")
cx1 = st.sidebar.number_input("Column width 1 cx (m)", value=0.30, step=0.1, format="%.3f")
cy1 = st.sidebar.number_input("Column length 1 cy (m)", value=0.30, step=0.1, format="%.3f")

st.sidebar.caption("For **second** column:")
P_D2 = st.sidebar.number_input("Dead axial load P_D2 (kN)", value=200.0, step=10.0, format="%.2f")
P_L2 = st.sidebar.number_input("Live axial load P_L2 (kN)", value=100.0, step=10.0, format="%.2f")
cx2 = st.sidebar.number_input("Column width 2 cx (m)", value=0.30, step=0.1, format="%.3f")
cy2 = st.sidebar.number_input("Column length 2 cy (m)", value=0.30, step=0.1, format="%.3f")

st.sidebar.caption("Footing limitations from the column's center:")
x1= st.sidebar.number_input("To the left of P1 (m)", value=0.0, step=0.1, format="%.2f")
x2= st.sidebar.number_input("To the right of P2 (m)", value=0.0, step=0.1, format="%.2f")

st.sidebar.caption("Other Design Parameters:")
t = st.sidebar.number_input("Footing thickness t (m)", min_value=0.05, value=0.50, step=0.1, format="%.3f")
d_f = st.sidebar.number_input("Foundation depth d_f (m)", min_value=0.0, value=0.00, step=0.1, format="%.3f")

gamma_s = st.sidebar.number_input("Unit weight of soil γ_s (kN/m³)", value=18.0, step=1.0, format="%.2f")
gamma_c = st.sidebar.number_input("Unit weight of concrete γ_c (kN/m³)", value=24.0, step=0.5, format="%.2f")
q_a = st.sidebar.number_input("Allowable soil pressure q_a (kPa)", value=200.0, step=10.0, format="%.2f")

fc_mp = st.sidebar.number_input("Concrete strength fc' (MPa)", min_value=10.0, value=25.0, step=1.0, format="%.2f")
fy_mp = st.sidebar.number_input("Yield strength of steel fy (MPa)", min_value=200.0, value=420.0, step=100.0, format="%.2f")

d_b_mm = st.sidebar.number_input("Main bar diameter d_b (mm)", min_value=6, value=16, step=1, format="%d")
cc_mm  = st.sidebar.number_input("Clear cover cc (mm)", min_value=5, value=50, step=1, format="%d")
st.sidebar.write(f"*Covering: {cc_mm + d_b_mm/2} mm.*")
